name: "Create Couchdb Cluster booter image"

on:
  push:
    paths:
      - docker/Dockerfile-booter
      - docker/init-cluster.sh
  workflow_dispatch: # on button click

jobs:
  test:
    strategy:
      matrix:
        node-version: [22]  # Add your desired versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to docker
        run: echo ${{ secrets.GH_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
      - name: Build Couchdb Booter
        run: docker build -t ghcr.io/decaf-ts/couchdb-booter:$(cat package.json | jq -r '.version') -t ghcr.io/decaf-ts/couchdb-booter:latest -f ./docker/Dockerfile-booter ./docker
      - name: Publish Couchdb Booter
        run: docker push ghcr.io/decaf-ts/couchdb-booter:$(cat package.json | jq -r '.version') && docker push ghcr.io/decaf-ts/couchdb-booter:latest